{% set name = "ngboost" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4bea289324c29b71aafe460e811cd4761bef698fa578b31a340a91e34cdc0350

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.17.2
    - scipy >=1.3.1
    - scikit-learn >=0.21.3
    - tqdm >=4.36.1
    - lifelines >=0.22.8

test:
  imports:
    - ngboost
    - ngboost.distns

about:
  home: https://github.com/stanfordmlgroup/ngboost
  license: Apache-2.0
  license_family: Apache
  # license file manually packaged. See tracking PR: https://github.com/stanfordmlgroup/ngboost/pull/178
  license_file: LICENSE
  summary: Natural Gradient Boosting for Probabilistic Prediction

  description: |
    'ngboost is a Python library that implements Natural Gradient Boosting,
    as described in "NGBoost:
    Natural Gradient Boosting for Probabilistic Prediction".
    It is built on top of Scikit-Learn,
    and is designed to be scalable and modular
    with respect to choice of
    proper scoring rule, distribution, and base learners.'


  doc_url: https://github.com/stanfordmlgroup/ngboost
  dev_url: https://github.com/stanfordmlgroup/ngboost

extra:
  recipe-maintainers:
    - ericmjl
    - avati
    - synapticarbors
