{% set name = "ngboost" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62c1ce3f90e6903979f0a75b38f2be02febb1f7d646509ec87fbea695b8805f8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6
    - numpy >=1.17,<2.0
    - scipy >=1.3,<2.0
    - scikit-learn >=0.21,<0.24
    - tqdm >=4.36,<5.0
    - lifelines >=0.25,<0.29

test:
  imports:
    - ngboost
    - ngboost.distns

about:
  home: https://github.com/stanfordmlgroup/ngboost
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Natural Gradient Boosting for Probabilistic Prediction

  description: |
    'ngboost is a Python library that implements Natural Gradient Boosting,
    as described in "NGBoost:
    Natural Gradient Boosting for Probabilistic Prediction".
    It is built on top of Scikit-Learn,
    and is designed to be scalable and modular
    with respect to choice of
    proper scoring rule, distribution, and base learners.'


  doc_url: https://github.com/stanfordmlgroup/ngboost
  dev_url: https://github.com/stanfordmlgroup/ngboost

extra:
  recipe-maintainers:
    - ericmjl
    - avati
    - synapticarbors
