travis:
  secure:
    BINSTAR_TOKEN: nyeEs41gY9113mxub2eADbI1ehHWt19DhgKzOBzMulAGVO3VLx5W1DP8i6gY/iDFFe+bfj6txCW0KvLiz7kmUSSWDfByNg8vPbS/4pkl4fmIdJhvastIBAUZ+kn13thCEsvPRRGncVo3zhnt++sIzi0jIiokLnyq7oA98I3+cwzaR6RmMPoMrT6bZICgAh1vS+Ge8X51aQJYoNpZUDyrLe9W9eUGNu52QlxBhI+15vy7NJNs0NcLipPvMp3uqHjr+bCtiNyZKTQEPWMEc/O0XjDmjedbCH8tOs1lx9G+/XTktKLBgIEruazFcTIOIc0ojqUBa/K6Gikb0WyBCh5GdANb3Ldy1wBKEoYVeo9w9cXe2td5JjTbR0IvwVC6uluOaGbpxHuIbvwntDwASuYWDl2zntzl5/KBTi7Up/4C1HcD6hJcJJY8rvHWuo93bK5QXWUF5Iz7Q6PNRsQNgkXiZ+nreyJmwmV5rQC4BWQN/QpcIXgtvFUAHs4YywoOk/sIKE4UqwK1TxRMiOYD5h3pUV8vSupo86f5zQg0MIA4/fd3ZnDW5RpbNsPBLFbDbc8deXh75NXyVaWtuDdoksbDNPqmS7Sq9Jl+htmAehwsQhSs9tupfieS4viMzGSexI5ziFtKBFWkTw6Kdl4txw+dkIxVVUyOvVijWMpc79ki56o=
conda_forge_output_validation: true
bot:
  automerge: true
